package inventoryManage

type ServiceGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue/server Begin; DO NOT EDIT.

	OutStockService
	// Code generated by github.com/tongxz/xs-admin-vue/server End; DO NOT EDIT.
}
