package inventoryManage

type ServiceGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue Begin; DO NOT EDIT.

	OutStockService
	WarehousingService
	// Code generated by github.com/tongxz/xs-admin-vue End; DO NOT EDIT.
}
