package member

type ServiceGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue Begin; DO NOT EDIT.

	MemberService
	RechargeService
	// Code generated by github.com/tongxz/xs-admin-vue End; DO NOT EDIT.
}
