package financial

type RouterGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue/server Begin; DO NOT EDIT.

	IncomeRouter
	ExpensesRouter
	// Code generated by github.com/tongxz/xs-admin-vue/server End; DO NOT EDIT.
}
