package financial

type ServiceGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue/server Begin; DO NOT EDIT.

	IncomeService
	ExpensesService
	// Code generated by github.com/tongxz/xs-admin-vue/server End; DO NOT EDIT.
}
