package inventoryManage

type ApiGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue Begin; DO NOT EDIT.

	OutStockApi
	WarehousingApi
	// Code generated by github.com/tongxz/xs-admin-vue End; DO NOT EDIT.
}
