package inventoryManage

type ApiGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue/server Begin; DO NOT EDIT.

	OutStockApi
	// Code generated by github.com/tongxz/xs-admin-vue/server End; DO NOT EDIT.
}
