package member

type ApiGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue Begin; DO NOT EDIT.

	MemberApi
	RechargeApi
	// Code generated by github.com/tongxz/xs-admin-vue End; DO NOT EDIT.
}
