package inventoryManage

type RouterGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue/server Begin; DO NOT EDIT.

	OutStockRouter
	// Code generated by github.com/tongxz/xs-admin-vue/server End; DO NOT EDIT.
}
