package inventoryManage

type RouterGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue Begin; DO NOT EDIT.

	OutStockRouter
	WarehousingRouter
	// Code generated by github.com/tongxz/xs-admin-vue End; DO NOT EDIT.
}
