package member

type RouterGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue Begin; DO NOT EDIT.

	MemberRouter
	// Code generated by github.com/tongxz/xs-admin-vue End; DO NOT EDIT.
}
