package financial

type ApiGroup struct {
	// Code generated by github.com/tongxz/xs-admin-vue/server Begin; DO NOT EDIT.

	IncomeApi
	ExpensesApi
	// Code generated by github.com/tongxz/xs-admin-vue/server End; DO NOT EDIT.
}
